# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('bed', models.CharField(max_length=50)),
                ('bed_quantity', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('amenities', models.CharField(max_length=50)),
            ],
        ),
    ]
