# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0005_auto_20190426_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('amount', models.FloatField()),
                ('notes', models.CharField(max_length=500)),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapp.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapp.Room')),
            ],
        ),
    ]
