# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsapp.Room')),
            ],
        ),
    ]
