# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0007_room_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start',
            new_name='checkout',
        ),
    ]
