# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0008_auto_20190426_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=3999),
            preserve_default=False,
        ),
    ]
