# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0015_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='name',
            new_name='_type',
        ),
        migrations.AddField(
            model_name='amenities',
            name='description',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
